# Generated by Django 4.0.3 on 2022-08-06 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.TextField(blank=True, null=True)),
                ('course', models.TextField(blank=True, null=True)),
                ('typee', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('dis', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='rc/')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
