# Generated by Django 4.0.3 on 2022-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_alter_rc_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc',
            name='course',
            field=models.TextField(blank=True, null=True),
        ),
    ]
