# Generated by Django 4.0.3 on 2022-08-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rc_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='rc',
            name='typee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typee'),
        ),
    ]
