# Generated by Django 4.0.3 on 2022-08-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='typee',
            name='img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
