# Generated by Django 4.0.3 on 2022-08-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_img_typee_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
