# Generated by Django 4.0.3 on 2022-08-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav',
            field=models.ManyToManyField(blank=True, to='core.rc'),
        ),
    ]
